# Connections settings for Mattermost
MATTERMAIL_MATTERMOST_URL: https://mattermost.example.com
MATTERMAIL_MATTERMOST_TEAM: opencraft
MATTERMAIL_MATTERMOST_LOGIN: mattermail
MATTERMAIL_MATTERMOST_PASSWORD: set-me-please
MATTERMAIL_MATTERMOST_CHANNEL: hosting-subteam

# Mattermail settings to fetch emails
EMAIL_SERVER: imap.example.com:143
EMAIL_USERNAME: urgent
EMAIL_PASSWORD: set-me-please

# Settings that can be left at their default values
MATTERMAIL_REPO: github.com/rodcorsi/mattermail
MATTERMAIL_BRANCH: master
MATTERMAIL_HOME: /opt/mattermail
