---
- name: install passlib for htpasswd generation
  apt:
    name: python3-passlib

- name: generate htpasswd file
  htpasswd:
    path: "{{ NGINX_PROXY_HTPASSWD_PATH }}"
    username: "{{ NGINX_PROXY_USERNAME }}"
    password: "{{ NGINX_PROXY_PASSWORD }}"

- name: set up nginx to reverse-proxy
  template:
    src: nginx-proxy.j2
    dest: "{{ NGINX_PROXY_CONFIG_PATH }}"
  notify:
    - reload nginx

- name: enable nginx site configuration
  file:
    src: "{{ NGINX_PROXY_CONFIG_PATH }}"
    dest: "/etc/nginx/sites-enabled/{{ NGINX_PROXY_CONFIG_PATH | basename }}"
    state: link
  notify:
    - reload nginx

- name: open public port on the firewall
  ufw:
    rule: allow
    port: "{{ NGINX_PROXY_PUBLIC_PORT }}"
    proto: tcp
